"""
Workout plan generation tool.

Generates a personalized 3-day workout plan based on user's
fitness level and goals, writing it to a text file.
"""

import os
from typing import Dict, Any


def generate_workout_plan(fitness_level: str, fitness_goals: str) -> Dict[str, Any]:
    """
    Generate a personalized workout plan and save it to a file.
    
    Args:
        fitness_level: User's fitness level (beginner, intermediate, advanced)
        fitness_goals: User's fitness goals (e.g., "build muscle", "lose weight")
    
    Returns:
        Dictionary with status and message about the generated plan
    """
    # Create outputs directory if it doesn't exist
    os.makedirs("outputs", exist_ok=True)
    
    # Generate workout plan based on fitness level and goals
    plan_content = _create_workout_plan_content(fitness_level, fitness_goals)
    
    # Write to file
    output_path = "outputs/workout_plan.txt"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(plan_content)
    
    return {
        "status": "success",
        "message": f"Workout plan generated successfully and saved to {output_path}",
        "file_path": output_path
    }


def _create_workout_plan_content(fitness_level: str, fitness_goals: str) -> str:
    """
    Create the workout plan content based on user's level and goals.
    
    Args:
        fitness_level: User's fitness level
        fitness_goals: User's fitness goals
    
    Returns:
        Formatted workout plan string
    """
    # Determine sets and reps based on fitness level
    if fitness_level.lower() == "beginner":
        sets = "2-3 sets"
        reps = "8-10 reps"
        rest = "60-90 seconds"
    elif fitness_level.lower() == "intermediate":
        sets = "3-4 sets"
        reps = "10-12 reps"
        rest = "45-60 seconds"
    else:  # advanced
        sets = "4-5 sets"
        reps = "12-15 reps"
        rest = "30-45 seconds"
    
    # Customize exercises based on goals
    if "muscle" in fitness_goals.lower() or "strength" in fitness_goals.lower():
        focus = "Strength Building"
        day1_exercises = "Push-ups, Dumbbell Press, Tricep Dips, Shoulder Press"
        day2_exercises = "Squats, Lunges, Deadlifts, Leg Press"
        day3_exercises = "Pull-ups, Rows, Bicep Curls, Lat Pulldowns"
    elif "weight" in fitness_goals.lower() or "fat" in fitness_goals.lower():
        focus = "Fat Loss & Cardio"
        day1_exercises = "HIIT Circuit: Burpees, Jumping Jacks, Mountain Climbers, High Knees"
        day2_exercises = "Strength Circuit: Squats, Push-ups, Lunges, Planks"
        day3_exercises = "Cardio: Running/Jogging, Cycling, Rowing, Jump Rope"
    elif "endurance" in fitness_goals.lower() or "cardio" in fitness_goals.lower():
        focus = "Endurance & Cardio"
        day1_exercises = "Long-distance running (30-45 min), Walking intervals"
        day2_exercises = "Cycling (30-45 min), Stair climbing"
        day3_exercises = "Swimming (30-45 min), Rowing machine"
    else:
        focus = "General Fitness"
        day1_exercises = "Push-ups, Squats, Planks, Jumping Jacks"
        day2_exercises = "Lunges, Burpees, Mountain Climbers, Leg Raises"
        day3_exercises = "Pull-ups, Dips, Russian Twists, High Knees"
    
    plan = f"""PERSONALIZED WORKOUT PLAN
{'=' * 50}

Fitness Level: {fitness_level.title()}
Fitness Goals: {fitness_goals}
Focus: {focus}

{'=' * 50}

DAY 1 - Upper Body / Cardio Focus
{'-' * 50}
Exercises: {day1_exercises}
Sets & Reps: {sets} of {reps} each
Rest Period: {rest} between sets
Duration: 45-60 minutes

DAY 2 - Lower Body / Strength Focus
{'-' * 50}
Exercises: {day2_exercises}
Sets & Reps: {sets} of {reps} each
Rest Period: {rest} between sets
Duration: 45-60 minutes

DAY 3 - Full Body / Active Recovery
{'-' * 50}
Exercises: {day3_exercises}
Sets & Reps: {sets} of {reps} each
Rest Period: {rest} between sets
Duration: 45-60 minutes

{'=' * 50}

IMPORTANT NOTES:
- Warm up for 5-10 minutes before each workout
- Cool down and stretch for 5-10 minutes after each workout
- Stay hydrated throughout your workouts
- Listen to your body and adjust intensity as needed
- Rest 1 day between workout days for recovery
- Progress gradually - consistency is key!

Generated by Gymbro AI Fitness Coach
"""
    
    return plan
